# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0004_auto_20171218_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderprofile',
            name='position',
            field=models.CharField(default=None, max_length=40, verbose_name='现任职位'),
        ),
    ]
