# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0005_auto_20171218_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderprofile',
            options={'ordering': ('id',), 'verbose_name': '领导人', 'verbose_name_plural': '领导人'},
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='month_of_birth',
            field=models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), (10, 10), (11, 11), (12, 12)], max_length=2, null=True, verbose_name='出生月份'),
        ),
    ]
