# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0006_auto_20171218_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderprofile',
            options={'verbose_name': '领导人', 'verbose_name_plural': '领导人'},
        ),
    ]
