# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0008_auto_20171219_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'male', '\u7537'), (b'female', '\u5973')], default=b'male', max_length=7, null=True, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='month_of_birth',
            field=models.CharField(blank=True, choices=[(b'01', b'01'), (b'02', b'02'), (b'03', b'03'), (b'04', b'04'), (b'05', b'05'), (b'06', b'06'), (b'07', b'07'), (b'08', b'08'), (b'09', b'09'), (10, 10), (11, 11), (12, 12)], max_length=2, null=True, verbose_name='\u51fa\u751f\u6708\u4efd'),
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='year_of_birth',
            field=models.CharField(blank=True, choices=[(1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998)], max_length=4, null=True, verbose_name='\u51fa\u751f\u5e74\u4efd'),
        ),
    ]
