# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0009_auto_20171219_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'male', '\u7537'), (b'female', '\u5973')], max_length=7, null=True, verbose_name='\u6027\u522b'),
        ),
    ]
