# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0010_auto_20171219_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderprofile',
            name='day_of_birth',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='\u51fa\u751f\u65e5'),
        ),
    ]
