# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0011_leaderprofile_day_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderprofile',
            name='day_of_birth',
        ),
        migrations.RemoveField(
            model_name='leaderprofile',
            name='month_of_birth',
        ),
        migrations.RemoveField(
            model_name='leaderprofile',
            name='year_of_birth',
        ),
        migrations.AddField(
            model_name='leaderprofile',
            name='birth',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u751f\u65e5'),
        ),
    ]
