# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0013_auto_20171219_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderprofile',
            name='birth',
            field=models.CharField(blank=True, help_text='\u683c\u5f0f: 1999-01-01 (\u6ca1\u6709\u7528*\u4ee3\u66ff)', max_length=15, null=True, verbose_name='\u751f\u65e5'),
        ),
    ]
