# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0014_auto_20171219_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderprofile',
            name='position',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u73b0\u4efb\u804c\u4f4d'),
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='purposed_position',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u62df\u4efb\u804c\u4f4d'),
        ),
    ]
