# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0014_auto_20171219_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=7, null=True, verbose_name='性别'),
        ),
    ]
