# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0015_auto_20171220_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderprofile',
            name='admin_name',
            field=models.CharField(default=None, max_length=20, verbose_name='\u5f55\u5165\u7528\u6237\u59d3\u540d'),
        ),
    ]
