# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0016_leaderprofile_admin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderprofile',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6c11\u65cf'),
        ),
    ]
