# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0017_auto_20171220_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderprofile',
            name='source',
            field=models.URLField(blank=True, null=True, verbose_name='\u539f\u6587\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='remark',
            field=models.TextField(default=None, verbose_name='\u539f\u6587'),
        ),
    ]
