# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0018_auto_20171220_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderprofile',
            name='admin_name',
        ),
        migrations.AddField(
            model_name='leaderprofile',
            name='admin_no',
            field=models.CharField(default=None, max_length=50, verbose_name='\u5f55\u5165\u7528\u6237\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='leaderprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaderprofile',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='leaderprofile',
            name='no',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='leaderprofile',
            name='review_notes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5ba1\u6838\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='leaderprofile',
            name='spider',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leaderprofile',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='birth',
            field=models.CharField(blank=True, help_text='\u683c\u5f0f: 1999-01-01 (\u6ca1\u6709\u7528*\u4ee3\u66ff)', max_length=30, null=True, verbose_name='\u751f\u65e5'),
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6c11\u65cf'),
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'male', '\u7537'), (b'female', '\u5973')], max_length=10, null=True, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='photo_img',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u56fe\u7247\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u51fa\u751f\u5730'),
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='position',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u73b0\u4efb\u804c\u4f4d'),
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='purposed_position',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u62df\u4efb\u804c\u4f4d'),
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='remark',
            field=models.CharField(default=None, max_length=1000, verbose_name='\u539f\u6587'),
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u539f\u6587\u5730\u5740'),
        ),
    ]
