# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 13:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0019_auto_20171221_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderprofile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
