# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0020_auto_20171221_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderprofile',
            options={'ordering': ('-id',), 'verbose_name': '\u9886\u5bfc\u4eba\u4fe1\u606f', 'verbose_name_plural': '\u9886\u5bfc\u4eba\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='leaderprofile',
            name='remark',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u539f\u6587'),
        ),
    ]
