# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0021_auto_20171221_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderprofile',
            name='no',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
