# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 18:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PunishmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default=None, max_length=50, unique=True)),
                ('admin_no', models.CharField(default=None, max_length=20, verbose_name='\u5f55\u5165\u7528\u6237\u59d3\u540d')),
                ('penalty_name', models.CharField(default=None, max_length=50, verbose_name='\u88ab\u5904\u7f5a\u673a\u6784\u540d\u79f0')),
                ('case_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6267\u884c\u6848\u53f7')),
                ('punished_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5904\u7f5a\u673a\u6784\u540d\u79f0')),
                ('company_unified_social_credit_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u7edf\u4e00\u793e\u4f1a\u4fe1\u7528\u4ee3\u7801')),
                ('organization_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7ec4\u7ec7\u673a\u6784\u4ee3\u7801')),
                ('business_registration_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5de5\u5546\u767b\u8bb0\u7801')),
                ('tax_registration_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7a0e\u52a1\u767b\u8bb0\u7801')),
                ('legal_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6cd5\u4eba')),
                ('penalty_results', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5904\u7f5a\u7ed3\u679c')),
                ('case_nature', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6848\u4ef6\u6027\u8d28')),
                ('disbelief_level', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5931\u4fe1\u7b49\u7ea7')),
                ('penalty_decision_date', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5904\u7f5a\u51b3\u5b9a\u65e5\u671f')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6570\u636e\u6765\u6e90')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8')),
                ('image_info', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u56fe\u7247\u4fe1\u606f')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u56fd\u5bb6\u7b80\u5199')),
                ('punished_basis', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5904\u7f5a\u4f9d\u636e')),
                ('punished_reason', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u5904\u7f5a\u539f\u56e0')),
                ('content', models.CharField(blank=True, max_length=2000, null=True, verbose_name='\u539f\u6587\u5185\u5bb9')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('spider', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name': '\u5904\u7f5a\u4fe1\u606f',
                'verbose_name_plural': '\u5904\u7f5a\u4fe1\u606f',
            },
        ),
    ]
