# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punishmentmodel',
            name='business_registration_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5de5\u5546\u767b\u8bb0\u7801'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='case_nature',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6848\u4ef6\u6027\u8d28'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='case_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6267\u884c\u6848\u53f7'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='company_unified_social_credit_code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u7edf\u4e00\u793e\u4f1a\u4fe1\u7528\u4ee3\u7801'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='content',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='\u539f\u6587\u5185\u5bb9'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u56fd\u5bb6\u7b80\u5199'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='disbelief_level',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5931\u4fe1\u7b49\u7ea7'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='image_info',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u56fe\u7247\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='legal_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6cd5\u4eba'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='organization_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7ec4\u7ec7\u673a\u6784\u4ee3\u7801'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='penalty_decision_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5904\u7f5a\u51b3\u5b9a\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='penalty_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u88ab\u5904\u7f5a\u673a\u6784\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='penalty_results',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5904\u7f5a\u7ed3\u679c'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='punished_basis',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5904\u7f5a\u4f9d\u636e'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='punished_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5904\u7f5a\u673a\u6784\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='punished_reason',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u5904\u7f5a\u539f\u56e0'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6570\u636e\u6765\u6e90'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='tax_registration_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7a0e\u52a1\u767b\u8bb0\u7801'),
        ),
    ]
