# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishment', '0003_auto_20171220_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='punishmentmodel',
            name='admin_name',
            field=models.CharField(default=None, max_length=20, verbose_name='\u5f55\u5165\u7528\u6237\u59d3\u540d'),
        ),
    ]
