# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishment', '0004_punishmentmodel_admin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punishmentmodel',
            name='penalty_name',
            field=models.CharField(default=None, max_length=50, verbose_name='\u88ab\u5904\u7f5a\u673a\u6784\u540d\u79f0'),
        ),
    ]
