# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishment', '0005_auto_20171221_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punishmentmodel',
            name='content',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='\u539f\u6587\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='punishmentmodel',
            name='punished_basis',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5904\u7f5a\u4f9d\u636e'),
        ),
        migrations.AlterField(
            model_name='punishmentmodel',
            name='punished_reason',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u5904\u7f5a\u539f\u56e0'),
        ),
    ]
