# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishment', '0006_auto_20171221_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punishmentmodel',
            old_name='admin_name',
            new_name='admin_no',
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='no',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='punishmentmodel',
            name='content',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='\u539f\u6587\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='punishmentmodel',
            name='punished_basis',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5904\u7f5a\u4f9d\u636e'),
        ),
        migrations.AlterField(
            model_name='punishmentmodel',
            name='punished_reason',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u5904\u7f5a\u539f\u56e0'),
        ),
    ]
