# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishment', '0007_auto_20171221_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='punishmentmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='punishmentmodel',
            name='spider',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
